import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Markdown Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Mater Dei
        </h1>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Blog</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Santo do Dia &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Brigida &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>Desenvolvido por{'  '}
            <span className={styles.madre}>Madre de Deus</span>
        </span>
      </footer>
    </div>
  )
}